bruno:
  versin: "1"
  title: Best Fetstore
  type: "collection"
  ignore:
    - "node_modules"
    - ".git"

update:
  ignore:
    addNew: true
    folders:
      - /pet/findByTags
      - /api/admin
    ids:
      - addPet
      - uploadFile

auth:
  type: bearer
  value:
    token: "{{accessToken}}"
  ignore:
    ids:
      - login
    folders:
      - /user
