bruno:
  versin: "1"
  name: Best Fetstore
  type: "collection"
  ignore:
    - "node_modules"
    - ".git"

source: "https://petstore.swagger.io/v2/swagger.json"
output: "example/output"

update:
  ignore:
    addNew: true
    folders:
      - /environments
      - /pet/findByTags
      # - /api/admin
    ids:
      - addPet
      - clearCart
      - uploadFile

auth:
  type: bearer
  bearer:
    token: "{{accessToken}}"
  ignore:
    ids:
      - login
    folders:
      - /user
